//home handwork books kitchen books clothes
export const cardsJson = [
  {
    "img": "./../../assets/img/gifts/01.PNG",
    "type": "handwork",
    "title": "Набор для вырезания, макетный нож, коврик для резки, линейка",
    "description": "https://www.wildberries.ru/catalog/159263457/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/02.PNG",
    "type": "kitchen",
    "title": "Форма силиконовая для аэрогриля",
    "description": "https://www.wildberries.ru/catalog/224866263/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/03.PNG",
    "type": "handwork",
    "title": "Набор сургуча в гранулах для печати",
    "description": "https://www.wildberries.ru/catalog/224522954/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/04.PNG",
    "type": "home",
    "title": "Ароматическая свеча для дома",
    "description": "https://www.wildberries.ru/catalog/191360644/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/05.PNG",
    "type": "home",
    "title": "Свечи светодиодные на батарейках 3 шт",
    "description": "https://www.wildberries.ru/catalog/182697244/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/06.PNG",
    "type": "clothes",
    "title": "Носки теплые зимние пушистые куница 5 пар",
    "description": "https://www.wildberries.ru/catalog/198146513/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/07.PNG",
    "type": "books",
    "title": "Закладки для книг самоклеящиеся, 12 шт",
    "description": "https://www.wildberries.ru/catalog/268288550/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/08.PNG",
    "type": "clothes",
    "title": "Серьги бижутерия круглые гвоздики пусеты",
    "description": "https://www.wildberries.ru/catalog/161755500/detail.aspx?targetUrl=SN",
  },  
  {
    "img": "./../../assets/img/gifts/09.PNG",
    "type": "kitchen",
    "title": "Круповарка MIKU для микроволновой печи, набор посуды",
    "description": "https://www.wildberries.ru/catalog/144627335/detail.aspx?targetUrl=SN",
  },  
  {
    "img": "./../../assets/img/gifts/10.PNG",
    "type": "home",
    "title": "Ароматизатор с палочками диффузор",
    "description": "https://www.wildberries.ru/catalog/187461106/detail.aspx?targetUrl=SN",
  },  
  {
    "img": "./../../assets/img/gifts/11.PNG",
    "type": "handwork",
    "title": "Набор деревянных штампов для скрапбукинга и творчества",
    "description": "https://www.wildberries.ru/catalog/155449180/detail.aspx?targetUrl=SN",
  },  
  {
    "img": "./../../assets/img/gifts/12.PNG",
    "type": "home",
    "title": "Стивен Кинг ароматическая свеча",
    "description": "https://www.wildberries.ru/catalog/133780268/detail.aspx?targetUrl=SN",
  },  
  {
    "img": "./../../assets/img/gifts/13.PNG",
    "type": "clothes",
    "title": "Серьги конго трансформеры кольца в подарок бижутерия",
    "description": "https://www.wildberries.ru/catalog/199744366/detail.aspx?targetUrl=SN",
  },  
  {
    "img": "./../../assets/img/gifts/14.PNG",
    "type": "books",
    "title": "Значок Книга The Hobbit из фильма Хоббит",
    "description": "https://www.wildberries.ru/catalog/237292134/detail.aspx?targetUrl=SN",
  },  
  {
    "img": "./../../assets/img/gifts/15.PNG",
    "type": "books",
    "title": "Значок Восточные Врата Мории из фильма Властелин колец",
    "description": "https://www.wildberries.ru/catalog/221565746/detail.aspx?targetUrl=SN",
  },  
  {
    "img": "./../../assets/img/gifts/16.PNG",
    "type": "home",
    "title": "Саше для белья в шкаф ароматическое 6 шт",
    "description": "https://www.wildberries.ru/catalog/66382517/detail.aspx?targetUrl=SN",
  },  
  {
    "img": "./../../assets/img/gifts/17.PNG",
    "type": "home",
    "title": "Конструктор 3D из миниблоков, Наруто",
    "description": "https://www.wildberries.ru/catalog/198738714/detail.aspx?targetUrl=SN",
  },  
  {
    "img": "./../../assets/img/gifts/18.PNG",
    "type": "clothes",
    "title": "косметичка маленькая в сумку на магните",
    "description": "https://www.wildberries.ru/catalog/98507954/detail.aspx?targetUrl=SN",
  },  
];