export const cardsJson = [
  {
    "img": "./../../assets/img/gifts/01.PNG",
    "type": "handwork",
    "title": "Набор для вышивания Маяк",
    "description": "https://www.wildberries.ru/catalog/251021712/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/02.PNG",
    "type": "handwork",
    "title": "Набор для вышивания Лиса",
    "description": "https://www.wildberries.ru/catalog/248924047/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/03.PNG",
    "type": "books",
    "title": "Сказания Древней Японии. Мифы и легенды. Коллекционное",
    "description": "https://www.wildberries.ru/catalog/214203910/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/04.PNG",
    "type": "kitchen",
    "title": "Подарочный набор специй и приправ премиум",
    "description": "https://www.wildberries.ru/catalog/180588202/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/05.PNG",
    "type": "handwork",
    "title": "Подарочный набор для каллиграфии Гарри Потер",
    "description": "https://www.wildberries.ru/catalog/215823832/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/06.PNG",
    "type": "handwork",
    "title": "Набор для скрапбукинга",
    "description": "https://www.wildberries.ru/catalog/174812348/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/07.PNG",
    "type": "home",
    "title": "Карандаш простой вечный с ластиком",
    "description": "https://www.wildberries.ru/catalog/154390352/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/08.PNG",
    "type": "home",
    "title": "Наклейки коты черные",
    "description": "https://www.wildberries.ru/catalog/12337277/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/09.PNG",
    "type": "home",
    "title": "Наклейки Лана",
    "description": "https://www.wildberries.ru/catalog/13807949/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/10.PNG",
    "type": "handwork",
    "title": "Деревянные штампы - набор Дни недели (12 шт)",
    "description": "https://www.wildberries.ru/catalog/211094665/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/11.PNG",
    "type": "handwork",
    "title": "Печать силиконовый штамп Хогвартс Факультеты",
    "description": "https://www.wildberries.ru/catalog/198159483/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/12.PNG",
    "type": "handwork",
    "title": 'Сургуч "звездочки" Золотой перламутровый / 250 шт',
    "description": "https://www.wildberries.ru/catalog/180316591/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/13.PNG",
    "type": "handwork",
    "title": "Набор для сборки пазлов",
    "description": "https://www.wildberries.ru/catalog/149052344/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/14.PNG",
    "type": "clothes",
    "title": "Шапка бини вязаная из хлопка весна",
    "description": "https://www.wildberries.ru/catalog/74033814/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/15.PNG",
    "type": "kitchen",
    "title": "Дуршлаг силиконовый",
    "description": "https://www.wildberries.ru/catalog/106282559/detail.aspx?targetUrl=SN",
  },
  {
    "img": "./../../assets/img/gifts/16.PNG",
    "type": "kitchen",
    "title": "Дуршлаг складной силиконовый сито",
    "description": "https://www.wildberries.ru/catalog/55165716/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/17.PNG",
    "type": "kitchen",
    "title": "Дуршлаг для промывки на раковину",
    "description": "https://www.wildberries.ru/catalog/110670339/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/18.PNG",
    "type": "home",
    "title": "Пуффендуй ароматическая свеча - Гарри Поттер",
    "description": "https://www.wildberries.ru/catalog/95570681/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/19.PNG",
    "type": "home",
    "title": "Ароматическая соевая свеча Рождество",
    "description": "https://www.wildberries.ru/catalog/133590825/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/20.PNG",
    "type": "home",
    "title": "Диффузор ароматизатор для дома",
    "description": "https://www.wildberries.ru/catalog/169548655/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/21.PNG",
    "type": "home",
    "title": "Ароматизатор для дома с палочками аромадиффузор 2025 год",
    "description": "https://www.wildberries.ru/catalog/181908497/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/22.PNG",
    "type": "handwork",
    "title": "Большой набор для скрапбукинга",
    "description": "https://www.wildberries.ru/catalog/103716469/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/23.PNG",
    "type": "home",
    "title": "Свеча ароматическая распределяющая Гарри Поттер",
    "description": "https://www.wildberries.ru/catalog/164359841/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/24.PNG",
    "type": "books",
    "title": "Мифы и легенды кельтов. Коллекционное издание",
    "description": "https://www.wildberries.ru/catalog/215138223/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/25.PNG",
    "type": "home",
    "title": "Brocard Василиса Прекрасная жен. духи группы Экстра 10 мл",
    "description": "https://www.wildberries.ru/catalog/218087773/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/26.PNG",
    "type": "handwork",
    "title": "Клей карандаш канцелярский ПВА 3 штуки",
    "description": "https://www.wildberries.ru/catalog/174702494/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/27.PNG",
    "type": "clothes",
    "title": "Носки набор теплые термоноски высокие",
    "description": "https://www.wildberries.ru/catalog/179814358/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/28.PNG",
    "type": "clothes",
    "title": "Термоноски 5 пар, зимние теплые",
    "description": "https://www.wildberries.ru/catalog/174783844/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/29.PNG",
    "type": "clothes",
    "title": "Термоноски 5 пар, зимние теплые",
    "description": "https://www.wildberries.ru/catalog/175045000/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/30.PNG",
    "type": "handwork",
    "title": "Набор стикеров Знаки Зодиака",
    "description": "https://www.wildberries.ru/catalog/190137562/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/31.PNG",
    "type": "handwork",
    "title": "Бумага для скрапбукинга Марки",
    "description": "https://www.wildberries.ru/catalog/207440794/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/32.PNG",
    "type": "handwork",
    "title": "Набор для сургучной печати в гранулах 10 цв, Нежность",
    "description": "https://www.wildberries.ru/catalog/169068059/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/33.PNG",
    "type": "handwork",
    "title": "Cургуч для печати в гранулах",
    "description": "https://www.wildberries.ru/catalog/208068839/detail.aspx?targetUrl=SN",
  },
  {    
    "img": "./../../assets/img/gifts/34.PNG",
    "type": "home",
    "title": "Лампа для чтения книг на прищепке Мини LED",
    "description": "https://www.wildberries.ru/catalog/242200105/detail.aspx?targetUrl=SN",
  },
];